### ISSUE TITLE
Google / Facebook login

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#18]
Both logins need to be implemented

**Comment by DennisMoosmann** [comment]
facebook available now

**Comment by T1m1** [comment]
:+1:

**Comment by T1m1** [comment]
Facebook login not working on mobile phones

**Comment by T1m1** [comment]
Google login error on ipad:

"
Error: invalid_request

ingalid parameter value for origin: missing authority: file://
"

**Comment by DennisMoosmann** [comment]
facebook works on mobile device

**Comment by DennisMoosmann** [comment]
google also working now
