### ISSUE TITLE
performance improvments

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/mobile#19]
https://quickleft.com/blog/4-steps-to-minimizing-rendering-issues-in-cordova-applications/

**Comment by T1m1** [comment]
remove 300ms delay from buttons
http://blog.ionic.io/hybrid-apps-and-the-curse-of-the-300ms-delay/

**Comment by T1m1** [comment]
use https://github.com/crosswalk-project/crosswalk

**Comment by T1m1** [comment]
http://stackoverflow.com/questions/29070389/ionic-framework-mobile-application-performance-issue

**Comment by timoweiss** [comment]
consider http://ionicframework.com/docs/api/directive/collectionRepeat/

**Comment by michaelknoch** [comment]
consider using crosswalk for android apks
http://ionicframework.com/docs/cli/browsers.html

tested with  crosswalk Version 12.41.296.5 and noticed huge performance improvement. The apk size exploded a bit but it could be split up into two apks (arm/intel) and we can submit them separately to play store. https://software.intel.com/en-us/xdk/docs/submitting-multiple-crosswalk-apk-to-google-play-store

**Comment by T1m1** [comment]
Added performance improvments:
- crosswalk 
- collectionRepeat
