### ISSUE TITLE
anschreiben // weiterleitung an chat

### ISSUE THREAD

**Issue by tschulo** [locator-kn/mobile#48]
wenn man auf anschreiben klickt,
sollte man anstatt zu dem:
![img_2612](https://cloud.githubusercontent.com/assets/12935497/8727647/1dca64f6-2be1-11e5-8f2a-d3b796664a07.PNG)

zu dem kommen:
![img_2613](https://cloud.githubusercontent.com/assets/12935497/8727649/23746af0-2be1-11e5-83f0-419c274c4071.PNG)

und wir brauchen dann noch ein: "zurück" button

**Comment by T1m1** [comment]
-> startConversation branch ... in progress
