### ISSUE TITLE
profile image isn't displayed after upload [caching bug]

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#63]

**Comment by timoweiss** [comment]
help wanted? @T1m1

**Comment by T1m1** [comment]
yes, please :+1:

**Comment by T1m1** [comment]
ready in your branch? :)

**Comment by timoweiss** [comment]
Should work:

https://github.com/locator-kn/mobile/blob/bugfix/updateProfileImage/www-develop/templates/profile.html#L14

https://github.com/locator-kn/mobile/blob/bugfix/updateProfileImage/www-develop/templates/profile.html#L43

https://github.com/locator-kn/mobile/blob/bugfix/updateProfileImage/www-develop/js/controller/userCtrl.ts#L181-L184
