### ISSUE TITLE
Insert google analytics

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#66]
https://blog.nraboy.com/2014/06/using-google-analytics-ionicframework/

**Comment by michaelknoch** [comment]
https://blog.nraboy.com/2014/06/using-google-analytics-ionicframework/

**Comment by T1m1** [comment]
implemented on branch https://github.com/locator-kn/mobile/tree/ga-support

IMPORTANT: use plugin version cordova-plugin-google-analytics@0.7.1
