### ISSUE TITLE
ansicht von "locations" einheitlich darstellen

### ISSUE THREAD

**Issue by tschulo** [locator-kn/mobile#69]
immer wenn locations gelistet werden, wäre es super, wenn es so aussehen würde wie bei "locations hinzufügen" beim trip erstellen... dass die nen abstand zum rand und zu einander haben und abgerundete ecken und so

**Comment by T1m1** [comment]
Breite muss noch gefixt werden:

![screenshot_2015-07-26-13-40-13](https://cloud.githubusercontent.com/assets/5616884/8893964/5f6766ea-33a5-11e5-8ce1-f35a2241086f.png)

**Comment by T1m1** [comment]
breite gefixt
