### ISSUE TITLE
deutlichere trennung bei tags - komma statt leertaste

### ISSUE THREAD

**Issue by tschulo** [locator-kn/mobile#71]
bei neue location,
bitte die tags durch kommas trennen und nicht durch leertaste

des wär killer :)

**Comment by T1m1** [comment]
Evtl. auch das vom Web implementieren -> Bei Android 4.4 muss darauf geachtet werden, dass das Plugin vom Web nicht funktioniert, weil man nicht erfährt welche Taste gedrückt wurde. Deshalb muss überprüft werden, was als letztes eingegeben wurde und dann die Funktionen des plugins aufrufen.
