### ISSUE TITLE
Use linear-gradient onlly in android version >= 4.1

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#80]
http://caniuse.com/#search=linear-gradient

http://ionicframework.com/docs/api/utility/ionic.Platform/

![image](https://cloud.githubusercontent.com/assets/5616884/8894690/87bceb9a-33c0-11e5-8511-cebf84eb037d.png)

**Comment by michaelknoch** [comment]
to test @T1m1

**Comment by T1m1** [comment]
läuft :+1:
