### ISSUE TITLE
SVG bug on android 

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#81]
![20150726091050](https://cloud.githubusercontent.com/assets/5616884/8894743/ef58bd6e-33c1-11e5-9797-3b46a009f6d8.jpg)
![20150726091051 1](https://cloud.githubusercontent.com/assets/5616884/8894742/ef572512-33c1-11e5-9fb9-bf688d406506.jpg)
![20150726091051 2](https://cloud.githubusercontent.com/assets/5616884/8894744/ef5cea4c-33c1-11e5-9cb5-584ee1132aeb.jpg)
![20150726091051 3](https://cloud.githubusercontent.com/assets/5616884/8894747/ef66a334-33c1-11e5-92a5-c61986bfcb34.jpg)
![20150726091051 4](https://cloud.githubusercontent.com/assets/5616884/8894745/ef61a172-33c1-11e5-8b9f-0a9fd32b9727.jpg)
![20150726091051](https://cloud.githubusercontent.com/assets/5616884/8894746/ef639b08-33c1-11e5-9d73-88308de10e94.jpg)

**Comment by tschulo** [comment]
sollen wir hier pngs nehmen?

**Comment by T1m1** [comment]
Ja, ich überprüfe das aber morgen nochmal. Evtl. können wir am CSS was machen

**Comment by T1m1** [comment]
now -> new bugs :laughing: 

![image](https://cloud.githubusercontent.com/assets/5616884/8927928/42d0dc38-351b-11e5-8095-b4b0fb186249.png)

![image](https://cloud.githubusercontent.com/assets/5616884/8927933/4b28cd0a-351b-11e5-885f-51b4ec7b4354.png)


BUT: => This works:
![image](https://cloud.githubusercontent.com/assets/5616884/8927943/630744ba-351b-11e5-90d1-b3caae494a21.png)

**Comment by T1m1** [comment]
possible solutions:
- we need a container around a img tag
- use a background image with fix height & witdh
