### ISSUE TITLE
diverse ui verbesserungen

### ISSUE THREAD

**Issue by tschulo** [locator-kn/mobile#82]
@timi: lass uns dazu doch morgen oder am dienstag telefonieren? 
also ihr könnt schon dran arbeiten, aber falls was unklar ist

![biete](https://cloud.githubusercontent.com/assets/12935497/8895321/44561cee-33d6-11e5-8369-50c4516a5039.jpg)
![schriftgrosse](https://cloud.githubusercontent.com/assets/12935497/8895322/4498c242-33d6-11e5-9d67-19d16944c652.jpg)
![suchergebnisse_erstellt von](https://cloud.githubusercontent.com/assets/12935497/8895324/449a01ac-33d6-11e5-997d-682951ffd46d.jpg)
![unterkunft](https://cloud.githubusercontent.com/assets/12935497/8895323/4499c96c-33d6-11e5-99ee-8b5863db9abc.jpg)

ich glaub da haben wir schon drüber gesprochen:
![edit-button_trips](https://cloud.githubusercontent.com/assets/12935497/8895338/e5c0d056-33d6-11e5-96c6-e1c079b1831e.jpg)

und ich glaub des steht schon auf deiner todo oder?:
(bei profil > meine trips)
![Uploading suchergebnisse_erstellt am.jpg…]()

**Comment by michaelknoch** [comment]
- abstand bei mood icon verbessert
- font sizes bei insert location angepasst
- user in den suchergebnissen verlinkt
- ugly border beim accommodation equipment chooser entfernt

**Comment by T1m1** [comment]
- uppercase in accommodation
- edit button
