### ISSUE TITLE
Implement delete trip

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#83]

**Comment by T1m1** [comment]
@tschulo design wird benötigt

**Comment by tschulo** [comment]
![trips_bearb_loschen_1](https://cloud.githubusercontent.com/assets/12935497/8906840/21cd9bec-3472-11e5-99aa-43c47cbce24b.jpg)
![trips_bearb_loschen_2](https://cloud.githubusercontent.com/assets/12935497/8906841/21f1ea38-3472-11e5-8d9c-ae4844f0203e.jpg)
