### ISSUE TITLE
text für zurück button entfernt

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/mobile#89]
bezüglich deinem problem habe ich die back-button texte einfach entfernt. ein arrow nach links reicht doch aus oder? dann hat die header-bar etwas mehr luft. Geht das klar? Timi feierts.

![](https://cloud.githubusercontent.com/assets/12935497/8895323/4499c96c-33d6-11e5-99ee-8b5863db9abc.jpg)

$ionicConfigProvider.backButton.previousTitleText(false);

**Comment by T1m1** [comment]
:+1:

**Comment by tschulo** [comment]
ich finds super... hatte sowas auch schon überlegt

**Comment by michaelknoch** [comment]
sehr gut
