### ISSUE TITLE
Publish Version 1.0.0

### ISSUE THREAD

**Issue by T1m1** [locator-kn/mobile#92]
- merge branch https://github.com/locator-kn/mobile/tree/ga-support
- remove debugger from code
- generate icons (ionic resources ios / ionic resources android)
- concatenate & minify css/js (our gulp or https://www.npmjs.com/package/gulp-uglifyjs)
- upgrade version/appId in config.xml
- remove bower files (https://www.npmjs.com/package/bower-clean)
- test after build/minify !!! (login/fb/google/takePicture/getPictureFromGallery/Geo/create-editTrip/create-editLocation/writeMsg/editProfile/search)
- publish on android: (http://ionicframework.com/docs/guide/publishing.html / https://coderwall.com/p/vvkyra/getting-started-with-ionic)
- publish on ios: http://www.raywenderlich.com/8003/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-1   http://www.raywenderlich.com/8045/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-2
- ...

**Comment by T1m1** [comment]
- branch merged
-debugger removed

**Comment by T1m1** [comment]
Perform Plugin Test: @michaelknoch 

Keyboard: - tabs verschwinden wenn keyboard offen
file/file-transfer: Hochladen eines Bildes / Gallery
geolocation: getCurrentPosition
googleAnalytics: consolenausgabe: "start google-analytics" aber nur aufm device
splashscreen: consolenausgabe: "hiding splash screen"
whiteliste: wenn man Daten aufm Device erhält
camera: foto schießen
inappbrowser: googleMaps öffnet sich aufm device
network-info: wenn kein Internet -> popups

**Comment by T1m1** [comment]
Android -> done

**Comment by michaelknoch** [comment]
ios -> done
